name: Deploy PartyKit

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npx partykit deploy
        env:
          GITHUB_TOKEN: ${{ secrets.PARTYKIT_GITHUB_TOKEN }}
          GITHUB_LOGIN: tsriram
